export const APP_ICONS: { name: string; url: string }[] = [
  { name: '_arrow_back', url: 'assets/icons/arrow-back.svg' },
  { name: '_arrow_forward', url: 'assets/icons/arrow-forward.svg' },
  { name: 'admin', url: 'assets/icons/admin.svg' },
  { name: 'admin-person', url: 'assets/icons/admin-person.svg' },
  { name: 'alarm', url: 'assets/icons/alarm.svg' },
  { name: 'add', url: 'assets/icons/add.svg' },
  { name: 'bingx-pf', url: 'assets/icons/bingx-pf.svg' },
  { name: 'bingx-sf', url: 'assets/icons/bingx-sf.svg' },
  { name: 'binance', url: 'assets/icons/binance-black.svg' },
  { name: 'bitcoin', url: 'assets/icons/bitcoin.svg' },
  { name: 'black-list', url: 'assets/icons/black-list.svg' },
  { name: 'check', url: 'assets/icons/check.svg' },
  { name: 'close', url: 'assets/icons/close.svg' },
  { name: 'cmc', url: 'assets/icons/cmp.svg' },
  { name: 'cloud_sync', url: 'assets/icons/cloud_sync.svg' },
  { name: 'coin-sorter', url: 'assets/icons/coin-sorter.svg' },
  { name: 'cg', url: 'assets/icons/cg.svg' },
  { name: 'data-object', url: 'assets/icons/data-object.svg' },
  { name: 'dashboard', url: 'assets/icons/dashboard.svg' },
  { name: 'delete', url: 'assets/icons/delete.svg' },
  { name: 'delete-gray', url: 'assets/icons/delete-gray.svg' },
  { name: 'developer-mode', url: 'assets/icons/developer-mode.svg' },
  {
    name: 'developer-mode-white',
    url: 'assets/icons/developer-mode-white.svg',
  },
  { name: 'edit', url: 'assets/icons/edit.svg' },
  { name: 'facebook', url: 'assets/icons/facebook.svg' },
  { name: 'flare', url: 'assets/icons/flare.svg' },
  { name: 'flowchart', url: 'assets/icons/flowchart.svg' },
  { name: 'github', url: 'assets/icons/github.svg' },
  { name: 'google-logo', url: 'assets/icons/google-logo.svg' },
  { name: 'info', url: 'assets/icons/info.svg' },
  { name: 'line-chart', url: 'assets/icons/line-chart.svg' },
  { name: 'local-atm', url: 'assets/icons/local-atm.svg' },
  { name: 'long-list', url: 'assets/icons/long-list.svg' },
  { name: 'magic', url: 'assets/icons/magic.svg' },
  { name: 'mop', url: 'assets/icons/mop.svg' },
  { name: 'mop-white', url: 'assets/icons/mop-white.svg' },
  { name: 'mintmark', url: 'assets/icons/mintmark.svg' },
  { name: 'pause', url: 'assets/icons/pause.svg' },
  { name: 'play', url: 'assets/icons/play.svg' },
  { name: 'reddit', url: 'assets/icons/reddit.svg' },
  { name: 'report', url: 'assets/icons/report.svg' },
  { name: 'reset-settings', url: 'assets/icons/reset-settings.svg' },
  { name: 'reset_focus', url: 'assets/icons/reset_focus.svg' },
  { name: 'send-from', url: 'assets/icons/send-from.svg' },
  { name: 'send-to', url: 'assets/icons/send-to.svg' },
  { name: 'server-person', url: 'assets/icons/server-person.svg' },
  { name: 'sorter', url: 'assets/icons/sorter.svg' },
  { name: 'sort-up', url: 'assets/icons/sort-up.svg' },
  { name: 'sort-down', url: 'assets/icons/sort-down.svg' },
  { name: 'telegram', url: 'assets/icons/telegram.svg' },
  { name: 'triggered-alarm', url: 'assets/icons/triggered-alarm.svg' },
  { name: 'tv', url: 'assets/icons/tv.svg' },
  { name: 'tv-white', url: 'assets/icons/tv-white.svg' },
  { name: 'twitter', url: 'assets/icons/twitter.svg' },
  { name: 'websocket', url: 'assets/icons/websocket.svg' },
  { name: 'ws', url: 'assets/icons/ws.svg' },
];
